struct person_t {
  str name;
  i32 age;
}

enum MY_ENUMS : i32 {
  ONE,
  TWO,
  THREE,
  FOUR,
  FIVE,
  SIX,
}

str name = "David";
i32 age = 23;
str occupation = "Programmer";
str address = "Tbilisi, Georgia";
bool is_available = false;
i32 result = age + 2;

str color = "darkgreen";
if is_available {
  str hello = "world";
}

if is_available {
  str my_string = "This is a relatively long string";
  if some_condition < 0 {
    i32 x = 1;
  }
}


